---
# Source: metallb-minikube/templates/address_settings.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-address-pool
  namespace: metallb-system
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  addresses:
    - 192.168.16.30-192.168.16.60
  autoAssign: true
---
# Source: metallb-minikube/templates/address_settings.yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement-default
  namespace: metallb-system
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ipAddressPools:
    - local-address-pool
